# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from banqi_training.proto import scheduler_pb2 as banqi__training_dot_proto_dot_scheduler__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in banqi_training/proto/scheduler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/scheduler.SchedulerService/GetInfo',
                request_serializer=banqi__training_dot_proto_dot_scheduler__pb2.GetInfoRequest.SerializeToString,
                response_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.GetInfoReply.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/scheduler.SchedulerService/GetTask',
                request_serializer=banqi__training_dot_proto_dot_scheduler__pb2.TaskRequest.SerializeToString,
                response_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.ReportEpisode = channel.unary_unary(
                '/scheduler.SchedulerService/ReportEpisode',
                request_serializer=banqi__training_dot_proto_dot_scheduler__pb2.EpisodeMeta.SerializeToString,
                response_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.EpisodeAck.FromString,
                _registered_method=True)
        self.GetNetwork = channel.unary_unary(
                '/scheduler.SchedulerService/GetNetwork',
                request_serializer=banqi__training_dot_proto_dot_scheduler__pb2.NetworkRequest.SerializeToString,
                response_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.NetworkInfo.FromString,
                _registered_method=True)
        self.RegisterNetwork = channel.unary_unary(
                '/scheduler.SchedulerService/RegisterNetwork',
                request_serializer=banqi__training_dot_proto_dot_scheduler__pb2.RegisterNetworkRequest.SerializeToString,
                response_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.RegisterNetworkAck.FromString,
                _registered_method=True)
        self.ReportMatchResult = channel.unary_unary(
                '/scheduler.SchedulerService/ReportMatchResult',
                request_serializer=banqi__training_dot_proto_dot_scheduler__pb2.MatchResult.SerializeToString,
                response_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.MatchResultAck.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/scheduler.SchedulerService/Heartbeat',
                request_serializer=banqi__training_dot_proto_dot_scheduler__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.HeartbeatReply.FromString,
                _registered_method=True)
        self.SignNetworkUpload = channel.unary_unary(
                '/scheduler.SchedulerService/SignNetworkUpload',
                request_serializer=banqi__training_dot_proto_dot_scheduler__pb2.SignNetworkUploadRequest.SerializeToString,
                response_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.SignNetworkUploadAck.FromString,
                _registered_method=True)
        self.ListEpisodes = channel.unary_unary(
                '/scheduler.SchedulerService/ListEpisodes',
                request_serializer=banqi__training_dot_proto_dot_scheduler__pb2.ListEpisodesRequest.SerializeToString,
                response_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.ListEpisodesReply.FromString,
                _registered_method=True)


class SchedulerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportEpisode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportMatchResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignNetworkUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEpisodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.GetInfoRequest.FromString,
                    response_serializer=banqi__training_dot_proto_dot_scheduler__pb2.GetInfoReply.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.TaskRequest.FromString,
                    response_serializer=banqi__training_dot_proto_dot_scheduler__pb2.TaskResponse.SerializeToString,
            ),
            'ReportEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportEpisode,
                    request_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.EpisodeMeta.FromString,
                    response_serializer=banqi__training_dot_proto_dot_scheduler__pb2.EpisodeAck.SerializeToString,
            ),
            'GetNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetwork,
                    request_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.NetworkRequest.FromString,
                    response_serializer=banqi__training_dot_proto_dot_scheduler__pb2.NetworkInfo.SerializeToString,
            ),
            'RegisterNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNetwork,
                    request_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.RegisterNetworkRequest.FromString,
                    response_serializer=banqi__training_dot_proto_dot_scheduler__pb2.RegisterNetworkAck.SerializeToString,
            ),
            'ReportMatchResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportMatchResult,
                    request_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.MatchResult.FromString,
                    response_serializer=banqi__training_dot_proto_dot_scheduler__pb2.MatchResultAck.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.HeartbeatRequest.FromString,
                    response_serializer=banqi__training_dot_proto_dot_scheduler__pb2.HeartbeatReply.SerializeToString,
            ),
            'SignNetworkUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.SignNetworkUpload,
                    request_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.SignNetworkUploadRequest.FromString,
                    response_serializer=banqi__training_dot_proto_dot_scheduler__pb2.SignNetworkUploadAck.SerializeToString,
            ),
            'ListEpisodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEpisodes,
                    request_deserializer=banqi__training_dot_proto_dot_scheduler__pb2.ListEpisodesRequest.FromString,
                    response_serializer=banqi__training_dot_proto_dot_scheduler__pb2.ListEpisodesReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scheduler.SchedulerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scheduler.SchedulerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SchedulerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/GetInfo',
            banqi__training_dot_proto_dot_scheduler__pb2.GetInfoRequest.SerializeToString,
            banqi__training_dot_proto_dot_scheduler__pb2.GetInfoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/GetTask',
            banqi__training_dot_proto_dot_scheduler__pb2.TaskRequest.SerializeToString,
            banqi__training_dot_proto_dot_scheduler__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/ReportEpisode',
            banqi__training_dot_proto_dot_scheduler__pb2.EpisodeMeta.SerializeToString,
            banqi__training_dot_proto_dot_scheduler__pb2.EpisodeAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/GetNetwork',
            banqi__training_dot_proto_dot_scheduler__pb2.NetworkRequest.SerializeToString,
            banqi__training_dot_proto_dot_scheduler__pb2.NetworkInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/RegisterNetwork',
            banqi__training_dot_proto_dot_scheduler__pb2.RegisterNetworkRequest.SerializeToString,
            banqi__training_dot_proto_dot_scheduler__pb2.RegisterNetworkAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportMatchResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/ReportMatchResult',
            banqi__training_dot_proto_dot_scheduler__pb2.MatchResult.SerializeToString,
            banqi__training_dot_proto_dot_scheduler__pb2.MatchResultAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/Heartbeat',
            banqi__training_dot_proto_dot_scheduler__pb2.HeartbeatRequest.SerializeToString,
            banqi__training_dot_proto_dot_scheduler__pb2.HeartbeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SignNetworkUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/SignNetworkUpload',
            banqi__training_dot_proto_dot_scheduler__pb2.SignNetworkUploadRequest.SerializeToString,
            banqi__training_dot_proto_dot_scheduler__pb2.SignNetworkUploadAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEpisodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scheduler.SchedulerService/ListEpisodes',
            banqi__training_dot_proto_dot_scheduler__pb2.ListEpisodesRequest.SerializeToString,
            banqi__training_dot_proto_dot_scheduler__pb2.ListEpisodesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
